### ISSUE TITLE
No documentation on return codes from functions

### ISSUE THREAD

**Issue by nkolban** [ibm-messaging/iotf-embeddedc#2]
The documentations says that many of the functions return return codes but there does not appear to be any documentation on what the possible return codes are nor what they might mean.

For example, I have coded a call to `connectiotf` and it has returned `5`.  I don't know if this good or bad?

**Comment by jeffdare** [comment]
Hi,
Yes sure I will document the return codes. The return codes that you see are from the base MQTT client. I will document that as well in the Embedded C client documentation.

**Comment by nkolban** [comment]
Thanks for the plan.  Normally one closes an issue after having resolved the issue ... not when it is merely planned to be resolved.

**Comment by jeffdare** [comment]
Sorry for the miss. Its updated now.
