### ISSUE TITLE
Not authorized from connect ...

### ISSUE THREAD

**Issue by nkolban** [ibm-messaging/iotf-embeddedc#3]
I have written and compiled the following application:

```
#include <stdio.h>
#include <iotfclient.h>
int main(int argc, char *argv[]) {
  Iotfclient client;
  int rc = initialize(&client,
    "f976sn", // orgId
    "mydt1",  // deviceType
    "myd1",   // deviceId
    "token",  // authMethod
    "R(57K2QB4X98b)P8HO" // authtoken
  );
  printf("initialize rc=%d\n", rc);
  rc = connectiotf(&client);
  printf("connectiotf rc=%d\n", rc);
}
```

I have plugged in the values from the creation of my IoT Foundation service as shown here:

<img width="561" alt="2016-02-02_15-01-44" src="https://cloud.githubusercontent.com/assets/3421732/12764356/de428c4c-c9be-11e5-9ecf-d73f893b60ac.png">

When I run the code, the following is my output:

```
initialize rc=0
connectiotf rc=5
```

Unfortunately I am failing to see what I have done wrong.  The return code is supposed to mean not authorized but yet I seem to have matched up all the parameters correctly.  I am at a loss on how to debug further.

To test further, I created a device.cfg file in the samples folder and populated it with:
```
org=f976sn
type=mydt1
id=myd1
auth-method=token
auth-token=R(57K2QB4X98b)P8HO
```

Upon running, it too fails:

```
$ ./sampleDevice 
Connection failed and returned rc = 5.
 Quitting..
```

To validate that a known case works, I wrote the following JavaScript app:

```
var Client = require("ibmiotf").IotfDevice;
var deviceClient = new Client({
  org: "f976sn",
  id: "myd1",
  type: "mydt1",
  "auth-method": "token",
  "auth-token": "R(57K2QB4X98b)P8HO"
});
deviceClient.on("connect", function() {
  console.log("We connected to IoT Foundation");
  
  console.log("Device is now publishing a message");
  deviceClient.publish("X1", "json", "Hello World",0);
  
  console.log("Device is now disconnecting");
  deviceClient.disconnect();
});
deviceClient.on("error", function(err) {
  console.log("We detected an error: " + err);
});
deviceClient.connect();
```

and it works perfectly ... I can see the message arriving at the server.

**Comment by jeffdare** [comment]
Hi,
Can you please try with the latest code. There was a bug that I fixed yest, that should solve your issue.

**Comment by nkolban** [comment]
I tried the latest code and that did indeed cure the problem.  Thanks for that.   In future, can I suggest that you don't close the Issue until the person who opened the issue either says it can be closed or they close it themselves.  A committer such as yourself can close an issue but an ordinary person like myself can not re-open it if you close it.   So if the code fix had not worked, I would have had to create a new issue to track  the problem.

**Comment by zafersn** [comment]
Hi @nkolban.  Have you used this library on esp-idf?
