### ISSUE TITLE
samples/device.cfg should be a template

### ISSUE THREAD

**Issue by nkolban** [ibm-messaging/iotf-embeddedc#4]
The file called `samples/device.cfg` is empty.  This issue asks for it to be changed to a template for example:

```
org=$orgId
type=$myDeviceType
id=$myDeviceId
auth-method=token
auth-token=$token
```
such that it can be edited and the blanks/options filled in.

**Comment by jeffdare** [comment]
Hi,
Thanks for your valid input. Now the device.cfg has the template. 
Thanks!
